import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const sourcePath = path.join(root, "updates.json");
const outputPath = path.join(root, "public", "feed.xml");
const data = JSON.parse(await readFile(sourcePath, "utf8"));

function escapeXml(value) {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

function absoluteUrl(value) {
  return new URL(value, data.site.base).href;
}

function rssDate(date) {
  return new Date(`${date}T16:00:00Z`).toUTCString();
}

const updates = [...data.updates].sort((a, b) => b.date.localeCompare(a.date));
const lastBuildDate = updates.length > 0 ? rssDate(updates[0].date) : new Date().toUTCString();
const feedUrl = absoluteUrl("feed.xml");
const items = updates
  .map((update) => {
    const categories = update.tags
      .map((tag) => `      <category>${escapeXml(tag)}</category>`)
      .join("\n");
    const tagPrefix = update.tags.length > 0 ? `[${update.tags.join(", ")}] ` : "";

    return `    <item>
      <title>${escapeXml(`${update.tool} — ${update.title}`)}</title>
      <link>${escapeXml(absoluteUrl(update.link))}</link>
      <description>${escapeXml(`${tagPrefix}${update.summary}`)}</description>
      <pubDate>${rssDate(update.date)}</pubDate>
      <guid isPermaLink="false">copilot-analytics-labs:${escapeXml(update.id)}</guid>
${categories}
    </item>`;
  })
  .join("\n");

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/build-feed.mjs from updates.json. Do not edit by hand. -->
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>${escapeXml(data.site.title)}</title>
    <link>${escapeXml(data.site.base)}</link>
    <description>${escapeXml(data.site.description)}</description>
    <language>en</language>
    <lastBuildDate>${lastBuildDate}</lastBuildDate>
    <ttl>1440</ttl>
    <atom:link href="${escapeXml(feedUrl)}" rel="self" type="application/rss+xml" />
${items}
  </channel>
</rss>
`;

await writeFile(outputPath, xml, "utf8");
console.log(`Generated ${path.relative(root, outputPath)}`);
